// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Metrics
{
    /// <summary> The parameters for a single metrics query. </summary>
    public partial class MetricsPostBodySchemaParameters
    {
        /// <summary> Initializes a new instance of MetricsPostBodySchemaParameters. </summary>
        /// <param name="metricId"> . </param>
        public MetricsPostBodySchemaParameters(MetricId metricId)
        {
            MetricId = metricId;
            Aggregation = new List<MetricsAggregation>();
            Segment = new List<MetricsSegment>();
        }

        public MetricId MetricId { get; }
        /// <summary> The timespan over which to retrieve metric values. This is an ISO8601 time period value. If timespan is omitted, a default time range of `PT12H` (&quot;last 12 hours&quot;) is used. The actual timespan that is queried may be adjusted by the server based. In all cases, the actual time span used for the query is included in the response. </summary>
        public string Timespan { get; set; }
        /// <summary> The aggregation to use when computing the metric values. To retrieve more than one aggregation at a time, separate them with a comma. If no aggregation is specified, then the default aggregation for the metric is used. </summary>
        public IList<MetricsAggregation> Aggregation { get; }
        /// <summary> The time interval to use when retrieving metric values. This is an ISO8601 duration. If interval is omitted, the metric value is aggregated across the entire timespan. If interval is supplied, the server may adjust the interval to a more appropriate size based on the timespan used for the query. In all cases, the actual interval used for the query is included in the response. </summary>
        public TimeSpan? Interval { get; set; }
        /// <summary> The name of the dimension to segment the metric values by. This dimension must be applicable to the metric you are retrieving. To segment by more than one dimension at a time, separate them with a comma (,). In this case, the metric data will be segmented in the order the dimensions are listed in the parameter. </summary>
        public IList<MetricsSegment> Segment { get; }
        /// <summary> The number of segments to return.  This value is only valid when segment is specified. </summary>
        public int? Top { get; set; }
        /// <summary> The aggregation function and direction to sort the segments by.  This value is only valid when segment is specified. </summary>
        public string Orderby { get; set; }
        /// <summary> An expression used to filter the results.  This value should be a valid OData filter expression where the keys of each clause should be applicable dimensions for the metric you are retrieving. </summary>
        public string Filter { get; set; }
    }
}
