// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Metrics
{
    /// <summary> A metric result. </summary>
    public partial class MetricsResult
    {
        /// <summary> Initializes a new instance of MetricsResult. </summary>
        internal MetricsResult()
        {
        }

        /// <summary> Initializes a new instance of MetricsResult. </summary>
        /// <param name="value"> A metric result data. </param>
        internal MetricsResult(MetricsResultInfo value)
        {
            Value = value;
        }

        /// <summary> A metric result data. </summary>
        public MetricsResultInfo Value { get; }
    }
}
