// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections;

namespace ApplicationCore.Models.AppInsights.Metrics
{
    /// <summary> A metric result data. </summary>
    public partial class MetricsResultInfo : IReadOnlyDictionary<string, object>
    {
        /// <summary> Initializes a new instance of MetricsResultInfo. </summary>
        internal MetricsResultInfo()
        {
            Segments = new List<MetricsSegmentInfo>();
            AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary> Initializes a new instance of MetricsResultInfo. </summary>
        /// <param name="start"> Start time of the metric. </param>
        /// <param name="end"> Start time of the metric. </param>
        /// <param name="interval"> The interval used to segment the metric data. </param>
        /// <param name="segments"> Segmented metric data (if segmented). </param>
        /// <param name="additionalProperties"> . </param>
        internal MetricsResultInfo(string start, string end, TimeSpan? interval, IReadOnlyList<MetricsSegmentInfo> segments, IReadOnlyDictionary<string, object> additionalProperties)
        {
            Start = start;
            End = end;
            Interval = interval;
            Segments = segments;
            AdditionalProperties = additionalProperties;
        }

        /// <summary> Start time of the metric. </summary>
        public string Start { get; }
        /// <summary> Start time of the metric. </summary>
        public string End { get; }
        /// <summary> The interval used to segment the metric data. </summary>
        public TimeSpan? Interval { get; }
        /// <summary> Segmented metric data (if segmented). </summary>
        public IReadOnlyList<MetricsSegmentInfo> Segments { get; }
        internal IReadOnlyDictionary<string, object> AdditionalProperties { get; }
        /// <inheritdoc />
        public IEnumerator<KeyValuePair<string, object>> GetEnumerator() => AdditionalProperties.GetEnumerator();
        /// <inheritdoc />
        IEnumerator IEnumerable.GetEnumerator() => AdditionalProperties.GetEnumerator();
        /// <inheritdoc />
        public bool TryGetValue(string key, out object value) => AdditionalProperties.TryGetValue(key, out value);
        /// <inheritdoc />
        public bool ContainsKey(string key) => AdditionalProperties.ContainsKey(key);
        /// <inheritdoc />
        public IEnumerable<string> Keys => AdditionalProperties.Keys;
        /// <inheritdoc />
        public IEnumerable<object> Values => AdditionalProperties.Values;
        /// <inheritdoc cref="IReadOnlyCollection{T}.Count"/>
        int IReadOnlyCollection<KeyValuePair<string, object>>.Count => AdditionalProperties.Count;
        /// <inheritdoc />
        public object this[string key]
        {
            get => AdditionalProperties[key];
        }
    }
}
