// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Metrics
{
    /// <summary> A metric request. </summary>
    public partial class MetricsPostBodySchema
    {
        /// <summary> Initializes a new instance of MetricsPostBodySchema. </summary>
        /// <param name="id"> An identifier for this query.  Must be unique within the post body of the request.  This identifier will be the &apos;id&apos; property of the response object representing this query. </param>
        /// <param name="parameters"> The parameters for a single metrics query. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> or <paramref name="parameters"/> is null. </exception>
        public MetricsPostBodySchema(string id, MetricsPostBodySchemaParameters parameters)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (parameters == null)
            {
                throw new ArgumentNullException(nameof(parameters));
            }

            Id = id;
            Parameters = parameters;
        }

        /// <summary> An identifier for this query.  Must be unique within the post body of the request.  This identifier will be the &apos;id&apos; property of the response object representing this query. </summary>
        public string Id { get; }
        /// <summary> The parameters for a single metrics query. </summary>
        public MetricsPostBodySchemaParameters Parameters { get; }
    }
}
