// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> Client info for an event result. </summary>
    public partial class EventsClientInfo
    {
        /// <summary> Initializes a new instance of EventsClientInfo. </summary>
        internal EventsClientInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsClientInfo. </summary>
        /// <param name="model"> Model of the client. </param>
        /// <param name="os"> Operating system of the client. </param>
        /// <param name="type"> Type of the client. </param>
        /// <param name="browser"> Browser of the client. </param>
        /// <param name="ip"> IP address of the client. </param>
        /// <param name="city"> City of the client. </param>
        /// <param name="stateOrProvince"> State or province of the client. </param>
        /// <param name="countryOrRegion"> Country or region of the client. </param>
        internal EventsClientInfo(string model, string os, string type, string browser, string ip, string city, string stateOrProvince, string countryOrRegion)
        {
            Model = model;
            Os = os;
            Type = type;
            Browser = browser;
            Ip = ip;
            City = city;
            StateOrProvince = stateOrProvince;
            CountryOrRegion = countryOrRegion;
        }

        /// <summary> Model of the client. </summary>
        public string Model { get; }
        /// <summary> Operating system of the client. </summary>
        public string Os { get; }
        /// <summary> Type of the client. </summary>
        public string Type { get; }
        /// <summary> Browser of the client. </summary>
        public string Browser { get; }
        /// <summary> IP address of the client. </summary>
        public string Ip { get; }
        /// <summary> City of the client. </summary>
        public string City { get; }
        /// <summary> State or province of the client. </summary>
        public string StateOrProvince { get; }
        /// <summary> Country or region of the client. </summary>
        public string CountryOrRegion { get; }
    }
}
