// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> AI related application info for an event result. </summary>
    public partial class EventsAiInfo
    {
        /// <summary> Initializes a new instance of EventsAiInfo. </summary>
        internal EventsAiInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsAiInfo. </summary>
        /// <param name="iKey"> iKey of the app. </param>
        /// <param name="appName"> Name of the application. </param>
        /// <param name="appId"> ID of the application. </param>
        /// <param name="sdkVersion"> SDK version of the application. </param>
        internal EventsAiInfo(string iKey, string appName, string appId, string sdkVersion)
        {
            IKey = iKey;
            AppName = appName;
            AppId = appId;
            SdkVersion = sdkVersion;
        }

        /// <summary> iKey of the app. </summary>
        public string IKey { get; }
        /// <summary> Name of the application. </summary>
        public string AppName { get; }
        /// <summary> ID of the application. </summary>
        public string AppId { get; }
        /// <summary> SDK version of the application. </summary>
        public string SdkVersion { get; }
    }
}
