// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> Operation info for an event result. </summary>
    public partial class EventsOperationInfo
    {
        /// <summary> Initializes a new instance of EventsOperationInfo. </summary>
        internal EventsOperationInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsOperationInfo. </summary>
        /// <param name="name"> Name of the operation. </param>
        /// <param name="id"> ID of the operation. </param>
        /// <param name="parentId"> Parent ID of the operation. </param>
        /// <param name="syntheticSource"> Synthetic source of the operation. </param>
        internal EventsOperationInfo(string name, string id, string parentId, string syntheticSource)
        {
            Name = name;
            Id = id;
            ParentId = parentId;
            SyntheticSource = syntheticSource;
        }

        /// <summary> Name of the operation. </summary>
        public string Name { get; }
        /// <summary> ID of the operation. </summary>
        public string Id { get; }
        /// <summary> Parent ID of the operation. </summary>
        public string ParentId { get; }
        /// <summary> Synthetic source of the operation. </summary>
        public string SyntheticSource { get; }
    }
}
