// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The custom metric info. </summary>
    public partial class EventsCustomMetricInfo
    {
        /// <summary> Initializes a new instance of EventsCustomMetricInfo. </summary>
        internal EventsCustomMetricInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsCustomMetricInfo. </summary>
        /// <param name="name"> The name of the custom metric. </param>
        /// <param name="value"> The value of the custom metric. </param>
        /// <param name="valueSum"> The sum of the custom metric. </param>
        /// <param name="valueCount"> The count of the custom metric. </param>
        /// <param name="valueMin"> The minimum value of the custom metric. </param>
        /// <param name="valueMax"> The maximum value of the custom metric. </param>
        /// <param name="valueStdDev"> The standard deviation of the custom metric. </param>
        internal EventsCustomMetricInfo(string name, double? value, double? valueSum, int? valueCount, double? valueMin, double? valueMax, double? valueStdDev)
        {
            Name = name;
            Value = value;
            ValueSum = valueSum;
            ValueCount = valueCount;
            ValueMin = valueMin;
            ValueMax = valueMax;
            ValueStdDev = valueStdDev;
        }

        /// <summary> The name of the custom metric. </summary>
        public string Name { get; }
        /// <summary> The value of the custom metric. </summary>
        public double? Value { get; }
        /// <summary> The sum of the custom metric. </summary>
        public double? ValueSum { get; }
        /// <summary> The count of the custom metric. </summary>
        public int? ValueCount { get; }
        /// <summary> The minimum value of the custom metric. </summary>
        public double? ValueMin { get; }
        /// <summary> The maximum value of the custom metric. </summary>
        public double? ValueMax { get; }
        /// <summary> The standard deviation of the custom metric. </summary>
        public double? ValueStdDev { get; }
    }
}
