// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The dependency info. </summary>
    public partial class EventsDependencyInfo
    {
        /// <summary> Initializes a new instance of EventsDependencyInfo. </summary>
        internal EventsDependencyInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsDependencyInfo. </summary>
        /// <param name="target"> The target of the dependency. </param>
        /// <param name="data"> The data of the dependency. </param>
        /// <param name="success"> Indicates if the dependency was successful. </param>
        /// <param name="duration"> The duration of the dependency. </param>
        /// <param name="performanceBucket"> The performance bucket of the dependency. </param>
        /// <param name="resultCode"> The result code of the dependency. </param>
        /// <param name="type"> The type of the dependency. </param>
        /// <param name="name"> The name of the dependency. </param>
        /// <param name="id"> The ID of the dependency. </param>
        internal EventsDependencyInfo(string target, string data, string success, long? duration, string performanceBucket, string resultCode, string type, string name, string id)
        {
            Target = target;
            Data = data;
            Success = success;
            Duration = duration;
            PerformanceBucket = performanceBucket;
            ResultCode = resultCode;
            Type = type;
            Name = name;
            Id = id;
        }

        /// <summary> The target of the dependency. </summary>
        public string Target { get; }
        /// <summary> The data of the dependency. </summary>
        public string Data { get; }
        /// <summary> Indicates if the dependency was successful. </summary>
        public string Success { get; }
        /// <summary> The duration of the dependency. </summary>
        public long? Duration { get; }
        /// <summary> The performance bucket of the dependency. </summary>
        public string PerformanceBucket { get; }
        /// <summary> The result code of the dependency. </summary>
        public string ResultCode { get; }
        /// <summary> The type of the dependency. </summary>
        public string Type { get; }
        /// <summary> The name of the dependency. </summary>
        public string Name { get; }
        /// <summary> The ID of the dependency. </summary>
        public string Id { get; }
    }
}
