// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> Client performance information. </summary>
    public partial class EventsClientPerformanceInfo
    {
        /// <summary> Initializes a new instance of EventsClientPerformanceInfo. </summary>
        internal EventsClientPerformanceInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsClientPerformanceInfo. </summary>
        /// <param name="name"> The name of the client performance. </param>
        internal EventsClientPerformanceInfo(string name)
        {
            Name = name;
        }

        /// <summary> The name of the client performance. </summary>
        public string Name { get; }
    }
}
