// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The availability result info. </summary>
    public partial class EventsAvailabilityResultInfo
    {
        /// <summary> Initializes a new instance of EventsAvailabilityResultInfo. </summary>
        internal EventsAvailabilityResultInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsAvailabilityResultInfo. </summary>
        /// <param name="name"> The name of the availability result. </param>
        /// <param name="success"> Indicates if the availability result was successful. </param>
        /// <param name="duration"> The duration of the availability result. </param>
        /// <param name="performanceBucket"> The performance bucket of the availability result. </param>
        /// <param name="message"> The message of the availability result. </param>
        /// <param name="location"> The location of the availability result. </param>
        /// <param name="id"> The ID of the availability result. </param>
        /// <param name="size"> The size of the availability result. </param>
        internal EventsAvailabilityResultInfo(string name, string success, long? duration, string performanceBucket, string message, string location, string id, string size)
        {
            Name = name;
            Success = success;
            Duration = duration;
            PerformanceBucket = performanceBucket;
            Message = message;
            Location = location;
            Id = id;
            Size = size;
        }

        /// <summary> The name of the availability result. </summary>
        public string Name { get; }
        /// <summary> Indicates if the availability result was successful. </summary>
        public string Success { get; }
        /// <summary> The duration of the availability result. </summary>
        public long? Duration { get; }
        /// <summary> The performance bucket of the availability result. </summary>
        public string PerformanceBucket { get; }
        /// <summary> The message of the availability result. </summary>
        public string Message { get; }
        /// <summary> The location of the availability result. </summary>
        public string Location { get; }
        /// <summary> The ID of the availability result. </summary>
        public string Id { get; }
        /// <summary> The size of the availability result. </summary>
        public string Size { get; }
    }
}
