// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The browser timing information. </summary>
    public partial class EventsBrowserTimingInfo
    {
        /// <summary> Initializes a new instance of EventsBrowserTimingInfo. </summary>
        internal EventsBrowserTimingInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsBrowserTimingInfo. </summary>
        /// <param name="urlPath"> The path of the URL. </param>
        /// <param name="urlHost"> The host of the URL. </param>
        /// <param name="name"> The name of the page. </param>
        /// <param name="url"> The url of the page. </param>
        /// <param name="totalDuration"> The total duration of the load. </param>
        /// <param name="performanceBucket"> The performance bucket of the load. </param>
        /// <param name="networkDuration"> The network duration of the load. </param>
        /// <param name="sendDuration"> The send duration of the load. </param>
        /// <param name="receiveDuration"> The receive duration of the load. </param>
        /// <param name="processingDuration"> The processing duration of the load. </param>
        internal EventsBrowserTimingInfo(string urlPath, string urlHost, string name, string url, long? totalDuration, string performanceBucket, long? networkDuration, long? sendDuration, long? receiveDuration, long? processingDuration)
        {
            UrlPath = urlPath;
            UrlHost = urlHost;
            Name = name;
            Url = url;
            TotalDuration = totalDuration;
            PerformanceBucket = performanceBucket;
            NetworkDuration = networkDuration;
            SendDuration = sendDuration;
            ReceiveDuration = receiveDuration;
            ProcessingDuration = processingDuration;
        }

        /// <summary> The path of the URL. </summary>
        public string UrlPath { get; }
        /// <summary> The host of the URL. </summary>
        public string UrlHost { get; }
        /// <summary> The name of the page. </summary>
        public string Name { get; }
        /// <summary> The url of the page. </summary>
        public string Url { get; }
        /// <summary> The total duration of the load. </summary>
        public long? TotalDuration { get; }
        /// <summary> The performance bucket of the load. </summary>
        public string PerformanceBucket { get; }
        /// <summary> The network duration of the load. </summary>
        public long? NetworkDuration { get; }
        /// <summary> The send duration of the load. </summary>
        public long? SendDuration { get; }
        /// <summary> The receive duration of the load. </summary>
        public long? ReceiveDuration { get; }
        /// <summary> The processing duration of the load. </summary>
        public long? ProcessingDuration { get; }
    }
}
