// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> A parsed stack entry. </summary>
    public partial class EventsExceptionDetailsParsedStack
    {
        /// <summary> Initializes a new instance of EventsExceptionDetailsParsedStack. </summary>
        internal EventsExceptionDetailsParsedStack()
        {
        }

        /// <summary> Initializes a new instance of EventsExceptionDetailsParsedStack. </summary>
        /// <param name="assembly"> The assembly of the stack entry. </param>
        /// <param name="method"> The method of the stack entry. </param>
        /// <param name="level"> The level of the stack entry. </param>
        /// <param name="line"> The line of the stack entry. </param>
        internal EventsExceptionDetailsParsedStack(string assembly, string method, long? level, long? line)
        {
            Assembly = assembly;
            Method = method;
            Level = level;
            Line = line;
        }

        /// <summary> The assembly of the stack entry. </summary>
        public string Assembly { get; }
        /// <summary> The method of the stack entry. </summary>
        public string Method { get; }
        /// <summary> The level of the stack entry. </summary>
        public long? Level { get; }
        /// <summary> The line of the stack entry. </summary>
        public long? Line { get; }
    }
}
