// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The custom event information. </summary>
    public partial class EventsCustomEventInfo
    {
        /// <summary> Initializes a new instance of EventsCustomEventInfo. </summary>
        internal EventsCustomEventInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsCustomEventInfo. </summary>
        /// <param name="name"> The name of the custom event. </param>
        internal EventsCustomEventInfo(string name)
        {
            Name = name;
        }

        /// <summary> The name of the custom event. </summary>
        public string Name { get; }
    }
}
