// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> Exception details. </summary>
    public partial class EventsExceptionDetail
    {
        /// <summary> Initializes a new instance of EventsExceptionDetail. </summary>
        internal EventsExceptionDetail()
        {
            ParsedStack = new List<EventsExceptionDetailsParsedStack>();
        }

        /// <summary> Initializes a new instance of EventsExceptionDetail. </summary>
        /// <param name="severityLevel"> The severity level of the exception detail. </param>
        /// <param name="outerId"> The outer ID of the exception detail. </param>
        /// <param name="message"> The message of the exception detail. </param>
        /// <param name="type"> The type of the exception detail. </param>
        /// <param name="id"> The ID of the exception detail. </param>
        /// <param name="parsedStack"> The parsed stack. </param>
        internal EventsExceptionDetail(string severityLevel, string outerId, string message, string type, string id, IReadOnlyList<EventsExceptionDetailsParsedStack> parsedStack)
        {
            SeverityLevel = severityLevel;
            OuterId = outerId;
            Message = message;
            Type = type;
            Id = id;
            ParsedStack = parsedStack;
        }

        /// <summary> The severity level of the exception detail. </summary>
        public string SeverityLevel { get; }
        /// <summary> The outer ID of the exception detail. </summary>
        public string OuterId { get; }
        /// <summary> The message of the exception detail. </summary>
        public string Message { get; }
        /// <summary> The type of the exception detail. </summary>
        public string Type { get; }
        /// <summary> The ID of the exception detail. </summary>
        public string Id { get; }
        /// <summary> The parsed stack. </summary>
        public IReadOnlyList<EventsExceptionDetailsParsedStack> ParsedStack { get; }
    }
}
