// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The performance counter info. </summary>
    public partial class EventsPerformanceCounterInfo
    {
        /// <summary> Initializes a new instance of EventsPerformanceCounterInfo. </summary>
        internal EventsPerformanceCounterInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsPerformanceCounterInfo. </summary>
        /// <param name="value"> The value of the performance counter. </param>
        /// <param name="name"> The name of the performance counter. </param>
        /// <param name="category"> The category of the performance counter. </param>
        /// <param name="counter"> The counter of the performance counter. </param>
        /// <param name="instanceName"> The instance name of the performance counter. </param>
        /// <param name="instance"> The instance of the performance counter. </param>
        internal EventsPerformanceCounterInfo(double? value, string name, string category, string counter, string instanceName, string instance)
        {
            Value = value;
            Name = name;
            Category = category;
            Counter = counter;
            InstanceName = instanceName;
            Instance = instance;
        }

        /// <summary> The value of the performance counter. </summary>
        public double? Value { get; }
        /// <summary> The name of the performance counter. </summary>
        public string Name { get; }
        /// <summary> The category of the performance counter. </summary>
        public string Category { get; }
        /// <summary> The counter of the performance counter. </summary>
        public string Counter { get; }
        /// <summary> The instance name of the performance counter. </summary>
        public string InstanceName { get; }
        /// <summary> The instance of the performance counter. </summary>
        public string Instance { get; }
    }
}
