// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The request info. </summary>
    public partial class EventsRequestInfo
    {
        /// <summary> Initializes a new instance of EventsRequestInfo. </summary>
        internal EventsRequestInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsRequestInfo. </summary>
        /// <param name="name"> The name of the request. </param>
        /// <param name="url"> The URL of the request. </param>
        /// <param name="success"> Indicates if the request was successful. </param>
        /// <param name="duration"> The duration of the request. </param>
        /// <param name="performanceBucket"> The performance bucket of the request. </param>
        /// <param name="resultCode"> The result code of the request. </param>
        /// <param name="source"> The source of the request. </param>
        /// <param name="id"> The ID of the request. </param>
        internal EventsRequestInfo(string name, string url, string success, double? duration, string performanceBucket, string resultCode, string source, string id)
        {
            Name = name;
            Url = url;
            Success = success;
            Duration = duration;
            PerformanceBucket = performanceBucket;
            ResultCode = resultCode;
            Source = source;
            Id = id;
        }

        /// <summary> The name of the request. </summary>
        public string Name { get; }
        /// <summary> The URL of the request. </summary>
        public string Url { get; }
        /// <summary> Indicates if the request was successful. </summary>
        public string Success { get; }
        /// <summary> The duration of the request. </summary>
        public double? Duration { get; }
        /// <summary> The performance bucket of the request. </summary>
        public string PerformanceBucket { get; }
        /// <summary> The result code of the request. </summary>
        public string ResultCode { get; }
        /// <summary> The source of the request. </summary>
        public string Source { get; }
        /// <summary> The ID of the request. </summary>
        public string Id { get; }
    }
}
