// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> The trace information. </summary>
    public partial class EventsTraceInfo
    {
        /// <summary> Initializes a new instance of EventsTraceInfo. </summary>
        internal EventsTraceInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsTraceInfo. </summary>
        /// <param name="message"> The trace message. </param>
        /// <param name="severityLevel"> The trace severity level. </param>
        internal EventsTraceInfo(string message, int? severityLevel)
        {
            Message = message;
            SeverityLevel = severityLevel;
        }

        /// <summary> The trace message. </summary>
        public string Message { get; }
        /// <summary> The trace severity level. </summary>
        public int? SeverityLevel { get; }
    }
}
