// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> Cloud info for an event result. </summary>
    public partial class EventsCloudInfo
    {
        /// <summary> Initializes a new instance of EventsCloudInfo. </summary>
        internal EventsCloudInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsCloudInfo. </summary>
        /// <param name="roleName"> Role name of the cloud. </param>
        /// <param name="roleInstance"> Role instance of the cloud. </param>
        internal EventsCloudInfo(string roleName, string roleInstance)
        {
            RoleName = roleName;
            RoleInstance = roleInstance;
        }

        /// <summary> Role name of the cloud. </summary>
        public string RoleName { get; }
        /// <summary> Role instance of the cloud. </summary>
        public string RoleInstance { get; }
    }
}
