// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Events
{
    /// <summary> Session info for an event result. </summary>
    public partial class EventsSessionInfo
    {
        /// <summary> Initializes a new instance of EventsSessionInfo. </summary>
        internal EventsSessionInfo()
        {
        }

        /// <summary> Initializes a new instance of EventsSessionInfo. </summary>
        /// <param name="id"> ID of the session. </param>
        internal EventsSessionInfo(string id)
        {
            Id = id;
        }

        /// <summary> ID of the session. </summary>
        public string Id { get; }
    }
}
