// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Metadata
{
    /// <summary> The metadata result for the app, including available tables, etc. </summary>
    public partial class MetadataResults
    {
        /// <summary> Initializes a new instance of MetadataResults. </summary>
        internal MetadataResults()
        {
            TableGroups = new List<MetadataTableGroup>();
            Tables = new List<MetadataTable>();
            Functions = new List<MetadataFunction>();
            Applications = new List<MetadataApplication>();
        }

        /// <summary> Initializes a new instance of MetadataResults. </summary>
        /// <param name="tableGroups"> The list of groups of tables on the app. </param>
        /// <param name="tables"> The list of tables and columns that comprise the schema of the app. </param>
        /// <param name="functions"> The list of functions stored on the app. </param>
        /// <param name="applications"> The list of Application Insights apps that were referenced in the metadata request. </param>
        internal MetadataResults(IReadOnlyList<MetadataTableGroup> tableGroups, IReadOnlyList<MetadataTable> tables, IReadOnlyList<MetadataFunction> functions, IReadOnlyList<MetadataApplication> applications)
        {
            TableGroups = tableGroups;
            Tables = tables;
            Functions = functions;
            Applications = applications;
        }

        /// <summary> The list of groups of tables on the app. </summary>
        public IReadOnlyList<MetadataTableGroup> TableGroups { get; }
        /// <summary> The list of tables and columns that comprise the schema of the app. </summary>
        public IReadOnlyList<MetadataTable> Tables { get; }
        /// <summary> The list of functions stored on the app. </summary>
        public IReadOnlyList<MetadataFunction> Functions { get; }
        /// <summary> The list of Application Insights apps that were referenced in the metadata request. </summary>
        public IReadOnlyList<MetadataApplication> Applications { get; }
    }
}
