// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Metadata
{
    /// <summary> The table grouping can be either an Application Insights schema or a Log Analytics solution. </summary>
    public partial class MetadataTableGroup
    {
        /// <summary> Initializes a new instance of MetadataTableGroup. </summary>
        /// <param name="id"> The ID of the table group. </param>
        /// <param name="name"> The name of the table group. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> or <paramref name="name"/> is null. </exception>
        internal MetadataTableGroup(string id, string name)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }

            Id = id;
            Name = name;
            Tables = new List<string>();
        }

        /// <summary> Initializes a new instance of MetadataTableGroup. </summary>
        /// <param name="id"> The ID of the table group. </param>
        /// <param name="name"> The name of the table group. </param>
        /// <param name="source"> The source of the table group, can be either AI or OMS for Log Analytics workspaces. </param>
        /// <param name="displayName"> The display name of the table group. </param>
        /// <param name="description"> The description of the table group. </param>
        /// <param name="tables"> The list of tables contained in the table group. </param>
        internal MetadataTableGroup(string id, string name, string source, string displayName, string description, IReadOnlyList<string> tables)
        {
            Id = id;
            Name = name;
            Source = source;
            DisplayName = displayName;
            Description = description;
            Tables = tables;
        }

        /// <summary> The ID of the table group. </summary>
        public string Id { get; }
        /// <summary> The name of the table group. </summary>
        public string Name { get; }
        /// <summary> The source of the table group, can be either AI or OMS for Log Analytics workspaces. </summary>
        public string Source { get; }
        /// <summary> The display name of the table group. </summary>
        public string DisplayName { get; }
        /// <summary> The description of the table group. </summary>
        public string Description { get; }
        /// <summary> The list of tables contained in the table group. </summary>
        public IReadOnlyList<string> Tables { get; }
    }
}
