// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Metadata
{
    /// <summary> Application Insights apps that were part of the metadata request and that the user has access to. </summary>
    public partial class MetadataApplication
    {
        /// <summary> Initializes a new instance of MetadataApplication. </summary>
        /// <param name="id"> The ID of the Application Insights app. </param>
        /// <param name="resourceId"> The ARM resource ID of the Application Insights app. </param>
        /// <param name="name"> The name of the Application Insights app. </param>
        /// <param name="region"> The Azure region of the Application Insights app. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/>, <paramref name="resourceId"/>, <paramref name="name"/>, or <paramref name="region"/> is null. </exception>
        internal MetadataApplication(string id, string resourceId, string name, string region)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (resourceId == null)
            {
                throw new ArgumentNullException(nameof(resourceId));
            }
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }
            if (region == null)
            {
                throw new ArgumentNullException(nameof(region));
            }

            Id = id;
            ResourceId = resourceId;
            Name = name;
            Region = region;
            Tables = new List<string>();
            Functions = new List<string>();
            TableGroups = new List<string>();
        }

        /// <summary> Initializes a new instance of MetadataApplication. </summary>
        /// <param name="id"> The ID of the Application Insights app. </param>
        /// <param name="resourceId"> The ARM resource ID of the Application Insights app. </param>
        /// <param name="name"> The name of the Application Insights app. </param>
        /// <param name="region"> The Azure region of the Application Insights app. </param>
        /// <param name="tables"> The list of custom tables for the Application Insights app. </param>
        /// <param name="functions"> The list of stored functions on the Application Insights app. </param>
        /// <param name="tableGroups"> The list of table groups on the Application Insights app. </param>
        internal MetadataApplication(string id, string resourceId, string name, string region, IReadOnlyList<string> tables, IReadOnlyList<string> functions, IReadOnlyList<string> tableGroups)
        {
            Id = id;
            ResourceId = resourceId;
            Name = name;
            Region = region;
            Tables = tables;
            Functions = functions;
            TableGroups = tableGroups;
        }

        /// <summary> The ID of the Application Insights app. </summary>
        public string Id { get; }
        /// <summary> The ARM resource ID of the Application Insights app. </summary>
        public string ResourceId { get; }
        /// <summary> The name of the Application Insights app. </summary>
        public string Name { get; }
        /// <summary> The Azure region of the Application Insights app. </summary>
        public string Region { get; }
        /// <summary> The list of custom tables for the Application Insights app. </summary>
        public IReadOnlyList<string> Tables { get; }
        /// <summary> The list of stored functions on the Application Insights app. </summary>
        public IReadOnlyList<string> Functions { get; }
        /// <summary> The list of table groups on the Application Insights app. </summary>
        public IReadOnlyList<string> TableGroups { get; }
    }
}
