// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

using System.Text.Json.Serialization;

#nullable disable

namespace ApplicationCore.Models.AppInsights.Queries
{
    /// <summary> Contains the tables, columns &amp; rows resulting from a query. </summary>
    public class QueryResults
    {
        public QueryResults()
        {
        }

        /// <summary> The list of tables, columns and rows. </summary>
        [JsonPropertyName("tables")]
        public List<Table> Tables { get; set; }
    }
}
