// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApplicationCore.Models.AppInsights.Queries
{
    /// <summary> Contains the tables, columns &amp; rows resulting from a query. </summary>
    public partial class QueryResults
    {

        /// <summary> Initializes a new instance of QueryResults. </summary>
        /// <param name="tables"> The list of tables, columns and rows. </param>
        public QueryResults(IReadOnlyList<Table> tables)
        {
            Tables = tables;
        }

        /// <summary> The list of tables, columns and rows. </summary>
        public IReadOnlyList<Table> Tables { get; }
    }
}
