// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

using System.Text.Json.Serialization;

#nullable disable

namespace ApplicationCore.Models.AppInsights.Queries
{
    /// <summary> Contains the columns and rows for one table in a query response. </summary>
    public class Table
    {
        public Table()
        {
        }

        /// <summary> The name of the table. </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }
        /// <summary> The list of columns in this table. </summary>
        [JsonPropertyName("columns")]
        public List<Column> Columns { get; set; }
        /// <summary> The resulting rows from this query. </summary>
        [JsonPropertyName("rows")]
        public List<IList<string>> Rows { get; set; }
    }
}
