// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

using System.Text.Json.Serialization;

#nullable disable

namespace ApplicationCore.Models.AppInsights.Queries
{
    /// <summary> Contains the columns and rows for one table in a query response. </summary>
    public class Table
    {
        public Table()
        {
        }
        /// <summary> Initializes a new instance of Table. </summary>
        /// <param name="name"> The name of the table. </param>
        /// <param name="columns"> The list of columns in this table. </param>
        /// <param name="rows"> The resulting rows from this query. </param>
        public Table(string name, List<Column> columns, List<IList<string>> rows)
        {
            Name = name;
            Columns = columns;
            Rows = rows;
        }

        /// <summary> The name of the table. </summary>
        public string Name { get; set; }
        /// <summary> The list of columns in this table. </summary>
        public List<Column> Columns { get; set; }
        /// <summary> The resulting rows from this query. </summary>
        public List<IList<string>> Rows { get; set; }
    }
}
